### ISSUE TITLE
Stuck on 'sign in with Microsoft account', cannot change to signing in with skype username

### ISSUE THREAD

**Issue by Nysosis** [bittner/skype#3] opened 2016-08-13 09:26 UTC
As per the title, at one time I've signed in with a microsoft account, logged out of it, and am now unable to sign in with a skype username - starting up the app is always defaulting to the microsoft account signin, with no way of going back to skype username

**Comment by bittner** [comment] 2016-08-13 22:51
Looks like this is by design from Microsoft. Interestingly, I can't reproduce this on the desktop: I don't even manage to find a "Login with Microsoft Account" option anymore. Strange.

I feel we can do little to fix this behavior. Microsoft should offer an option to switch to login using Skype user name, or simply also accept Skype user names in general, not just email addresses (which the Microsoft account identifiers essentially are).

## Quick Fix

If you're in desperate need to get this fixed on your mobile phone remove the app's `.local/share/...` directory in the phone's home directory: (use the Terminal app for this)

```
phablet@ubuntu-phablet:~$ rm -r ~/.local/share/skype.peter-bittner/
```

Optionally, you can also remove the app's `.cache/` and `.config/` directories to do a full clean-up:

```
phablet@ubuntu-phablet:~$ rm -r ~/.cache/skype.peter-bittner/
phablet@ubuntu-phablet:~$ rm -r ~/.config/skype.peter-bittner/
```

... then restart the Skype app.

**Comment by Nysosis** [comment] 2016-08-14 07:30
Thanks, I figured it would be more a microsoft thing. I'm happy to do the
cache clearing,

**Comment by bittner** [comment] 2016-08-14 13:25
@Nysosis You need to remove the `~/.local/share/skype.peter-bittner/` folder. I've updated my answer above.

**Closed as completed** 2016-08-14 13:25 UTC
Labels: wontfix
